### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by CodingNovice7** [POSTECH-CVLab/Combinatorial-3D-Shape-Generation#1]
Hello, thank you for your open source sharing. When I was reproducing your code, I found that there was a doubt. In the dataset you provided_ common. Py file, you have such a command: "from geometric_primitives import utils as utils_gp", but in my PIP installed geometric_ There is no utils file in the primitives package. Therefore, an error is reported: "cannot import name 'utils' from' geometric_primitives'.". Hope to get your help!

**Comment by jungtaekkim** [comment]
Hi @lylwy,

Thank you for your interests in our project.

I fixed errors.

If you have any additional issues, please let me know.

Best regards,
Jungtaek.
